# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI/CD

on:
  push:
    branches: [ main, develop, feature/clean-architecture ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: xcodebuild -version
    - run: |
        xcodebuild test \
          -scheme TODO \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -only-testing:TODOTests
